webtalk_init -webtalk_dir C:/Users/NicholasKimball/Documents/School/Senior/CPE439/QuadSLAM/Custom_IP/pwm_detector/pwm_detector.sim/sim_1/behav/xsim.dir/pwm_detector_sim_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Nov 14 01:07:21 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2016.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1577090" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210778909_1777507066_210600704_261" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "0cccc75088915d4cacd47142ae8d75f5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "b25bbb2358674afa89042869d106c107" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2893 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.22_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "17088_KB" -context "xsim\\usage"
webtalk_transmit -clientid 931001093 -regid "210778909_1777507066_210600704_261" -xml C:/Users/NicholasKimball/Documents/School/Senior/CPE439/QuadSLAM/Custom_IP/pwm_detector/pwm_detector.sim/sim_1/behav/xsim.dir/pwm_detector_sim_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/NicholasKimball/Documents/School/Senior/CPE439/QuadSLAM/Custom_IP/pwm_detector/pwm_detector.sim/sim_1/behav/xsim.dir/pwm_detector_sim_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/NicholasKimball/Documents/School/Senior/CPE439/QuadSLAM/Custom_IP/pwm_detector/pwm_detector.sim/sim_1/behav/xsim.dir/pwm_detector_sim_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
