# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/NicholasKimball/Documents/School/Senior/CPE439/QuadSLAM/Custom_IP/pwm_generator/pwm_generator.cache/wt [current_project]
set_property parent.project_path C:/Users/NicholasKimball/Documents/School/Senior/CPE439/QuadSLAM/Custom_IP/pwm_generator/pwm_generator.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/NicholasKimball/Documents/School/Senior/CPE439/QuadSLAM/Custom_IP/pwm_generator/pwm_generator.srcs [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/NicholasKimball/Documents/School/Senior/CPE439/QuadSLAM/Custom_IP/pwm_generator/pwm_generator.srcs/sources_1/new/pwm_generator_submodule.v
  C:/Users/NicholasKimball/Documents/School/Senior/CPE439/QuadSLAM/Custom_IP/pwm_generator/pwm_generator.srcs/sources_1/new/pwm_generator.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top pwm_generator -part xc7z010clg400-1


write_checkpoint -force -noxdef pwm_generator.dcp

catch { report_utilization -file pwm_generator_utilization_synth.rpt -pb pwm_generator_utilization_synth.pb }
